# Generated by Django 5.2.3 on 2025-07-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distribution_network", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networkparticipant",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                related_name="network_participant",
                to="distribution_network.product",
                verbose_name="Продукты",
            ),
        ),
    ]
