# Generated by Django 5.2.3 on 2025-07-04 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("distribution_network", "0002_alter_networkparticipant_products"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Продукт", "verbose_name_plural": "Продукты"},
        ),
    ]
